---
- name: Install Webserver, DB, Prom and Grafana
  hosts: all
  remote_user: root
  vars:
    mysql_root_password: "1234qwer"
    python_mysql: "{{ 'python3-mysqldb' if ansible_distribution|lower in ['debian', 'ubuntu'] else 'python3-PyMySQL' }}"
  roles:
    - apache
    - mysql
    - prometheus
    - grafana
# End
