- name: Install webserver and DB
  hosts: all
  remote_user: root
  vars:
    mysql_root_password: "1234qwer"
    python_mysql: "{{ 'python3-mysqldb' if ansible_distribution|lower in ['debian', 'ubuntu'] else 'python3-PyMySQL' }}"

  tasks:
  - name: Set APT as package Manager
    ansible.builtin.set_fact:
      package_manager: 'apt'
  
  - name: Install latest apache
    package:
      name: apache2
      state: latest
  
  - name: Install mariadb server and client
    package:
      name: mariadb-server
      state: latest
      update_cache: yes
    loop:
  
  - name: Install python mysql
    package:
      name: "{{ python_mysql }}"
      state: present
      update_cache: yes
  
  - name: start and enable mariadb server
    service:
      name: mariadb
      enabled: true
      state: started
  
  - name: update mysql root password for all root accounts  
    mysql_user:  
      name: root  
      host: "{{ item }}"  
      password: "{{ mysql_root_password }}"  
      login_user: root  
      login_password: "{{ mysql_root_password }}"  
      check_implicit_admin: yes  
      priv: "*.*:ALL,GRANT"  
    with_items:  
    - "{{ ansible_hostname }}"  
    - 127.0.0.1  
    - ::1  
    - localhost
  
  - name: Create a new database with name 'testdb'
    mysql_db:
      name: testdb
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"
  
  - name: Create database user with password & all database privileges and 'WITH GRANT OPTION'
    mysql_user:
      name: testuser
      password: ILikeTrains!
      priv: 'testdb.*:ALL'
      host: '%'
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"
