---
- name: Install latest MariaDB
  ansible.builtin.package:
    name: 
      - madiadb-server
      - madiadb-client
      - {{ python_mysql }}
    state: latest
    update_cache: true

- name: Start and enable mariadb server
  ansible.builtin.service:
    name: mariadb
    enabled: true
    state: started

- name: Update mysql root password for all root accounts  
  community.mysql.mysql_user:  
    name: root  
    host: "{{ item }}"  
    password: "{{ mysql_root_password }}"  
    login_user: root  
    login_password: "{{ mysql_root_password }}"  
    check_implicit_admin: true  
    priv: "*.*:ALL,GRANT"  
  with_items:  
  - "{{ ansible_hostname }}"  
  - 127.0.0.1  
  - ::1  
  - localhost

- name: Create a new database with name 'testdb'
  community.mysql.mysql_db:
    name: testdb
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create database user with password & all database privileges and 'WITH GRANT OPTION'
  community.mysql.mysql_user:
    name: testuser
    password: ILikeTrains!
    priv: 'testdb.*:ALL'
    host: '%'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
